spring.application.name=tutoudec

spring.datasource.url=jdbc:postgresql://localhost:5432/tutoudec_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=tutoudec_clave_super_secreta_2025_proyecto_semestre
jwt.expiration=86400000

spring.devtools.restart.enabled=false
spring.devtools.add-properties=false